// Generated by packages/tokens/build/build.mjs — DO NOT EDIT.
import SwiftUI
import UIKit

public enum HM {
  public enum color {
    public static let bgDefaultUI: UIColor = .hm(light: 0xFFFFFF, dark: 0x020617)
    public static var bgDefault: Color { Color(uiColor: bgDefaultUI) }
    public static let bgSubtleUI: UIColor = .hm(light: 0xF8FAFC, dark: 0x0F172A)
    public static var bgSubtle: Color { Color(uiColor: bgSubtleUI) }
    public static let bgMutedUI: UIColor = .hm(light: 0xF1F5F9, dark: 0x1E293B)
    public static var bgMuted: Color { Color(uiColor: bgMutedUI) }
    public static let bgInvertedUI: UIColor = .hm(light: 0x0F172A, dark: 0xF8FAFC)
    public static var bgInverted: Color { Color(uiColor: bgInvertedUI) }
    public static let fgDefaultUI: UIColor = .hm(light: 0x0F172A, dark: 0xF8FAFC)
    public static var fgDefault: Color { Color(uiColor: fgDefaultUI) }
    public static let fgMutedUI: UIColor = .hm(light: 0x475569, dark: 0x94A3B8)
    public static var fgMuted: Color { Color(uiColor: fgMutedUI) }
    public static let fgSubtleUI: UIColor = .hm(light: 0x94A3B8, dark: 0x64748B)
    public static var fgSubtle: Color { Color(uiColor: fgSubtleUI) }
    public static let fgInvertedUI: UIColor = .hm(light: 0xFFFFFF, dark: 0x0F172A)
    public static var fgInverted: Color { Color(uiColor: fgInvertedUI) }
    public static let fgLinkUI: UIColor = .hm(light: 0x2563EB, dark: 0x60A5FA)
    public static var fgLink: Color { Color(uiColor: fgLinkUI) }
    public static let borderDefaultUI: UIColor = .hm(light: 0xE2E8F0, dark: 0x1E293B)
    public static var borderDefault: Color { Color(uiColor: borderDefaultUI) }
    public static let borderStrongUI: UIColor = .hm(light: 0xCBD5E1, dark: 0x334155)
    public static var borderStrong: Color { Color(uiColor: borderStrongUI) }
    public static let borderFocusUI: UIColor = .hm(light: 0x3B82F6, dark: 0x3B82F6)
    public static var borderFocus: Color { Color(uiColor: borderFocusUI) }
    public static let actionPrimaryBgUI: UIColor = .hm(light: 0x2563EB, dark: 0x3B82F6)
    public static var actionPrimaryBg: Color { Color(uiColor: actionPrimaryBgUI) }
    public static let actionPrimaryHoverUI: UIColor = .hm(light: 0x1D4ED8, dark: 0x60A5FA)
    public static var actionPrimaryHover: Color { Color(uiColor: actionPrimaryHoverUI) }
    public static let actionPrimaryFgUI: UIColor = .hm(light: 0xFFFFFF, dark: 0xFFFFFF)
    public static var actionPrimaryFg: Color { Color(uiColor: actionPrimaryFgUI) }
    public static let statusDangerUI: UIColor = .hm(light: 0xDC2626, dark: 0xEF4444)
    public static var statusDanger: Color { Color(uiColor: statusDangerUI) }
    public static let statusSuccessUI: UIColor = .hm(light: 0x16A34A, dark: 0x22C55E)
    public static var statusSuccess: Color { Color(uiColor: statusSuccessUI) }
    public static let statusWarningUI: UIColor = .hm(light: 0xF59E0B, dark: 0xFBBF24)
    public static var statusWarning: Color { Color(uiColor: statusWarningUI) }
  }

  public enum space {
    public static let _0: CGFloat = 0
    public static let _1: CGFloat = 4
    public static let _2: CGFloat = 8
    public static let _3: CGFloat = 12
    public static let _4: CGFloat = 16
    public static let _5: CGFloat = 20
    public static let _6: CGFloat = 24
    public static let _8: CGFloat = 32
    public static let _10: CGFloat = 40
    public static let _12: CGFloat = 48
    public static let _16: CGFloat = 64
  }

  public enum radius {
    public static let sm: CGFloat = 4
    public static let md: CGFloat = 8
    public static let lg: CGFloat = 12
    public static let xl: CGFloat = 16
    public static let full: CGFloat = 9999
  }

  public enum fontSize {
    public static let xs: CGFloat = 12
    public static let sm: CGFloat = 14
    public static let md: CGFloat = 16
    public static let lg: CGFloat = 18
    public static let xl: CGFloat = 20
    public static let _2xl: CGFloat = 24
    public static let _3xl: CGFloat = 30
    public static let _4xl: CGFloat = 36
  }

  public enum fontWeight {
    public static let regular: Int = 400
    public static let medium: Int = 500
    public static let semibold: Int = 600
    public static let bold: Int = 700
    public static let extrabold: Int = 800
  }

  public enum lineHeight {
    public static let tight: CGFloat = 1.25
    public static let normal: CGFloat = 1.5
    public static let relaxed: CGFloat = 1.625
  }

  public enum typography {
    public static let headingLg = HMTextStyle(size: 30, weight: 700, lineHeight: 1.25)
    public static let headingMd = HMTextStyle(size: 24, weight: 600, lineHeight: 1.25)
    public static let headingSm = HMTextStyle(size: 20, weight: 600, lineHeight: 1.25)
    public static let bodyMd = HMTextStyle(size: 16, weight: 400, lineHeight: 1.5)
    public static let bodySm = HMTextStyle(size: 14, weight: 400, lineHeight: 1.5)
    public static let caption = HMTextStyle(size: 12, weight: 400, lineHeight: 1.5)
  }
}
