// Generated by packages/tokens/build/build.mjs — DO NOT EDIT.
package halfmoon.tokens

import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

object HM {
    object color {
        val bgDefault: Color @Composable @ReadOnlyComposable get() = hm(light = 0xFFFFFF, dark = 0x020617)
        val bgSubtle: Color @Composable @ReadOnlyComposable get() = hm(light = 0xF8FAFC, dark = 0x0F172A)
        val bgMuted: Color @Composable @ReadOnlyComposable get() = hm(light = 0xF1F5F9, dark = 0x1E293B)
        val bgInverted: Color @Composable @ReadOnlyComposable get() = hm(light = 0x0F172A, dark = 0xF8FAFC)
        val fgDefault: Color @Composable @ReadOnlyComposable get() = hm(light = 0x0F172A, dark = 0xF8FAFC)
        val fgMuted: Color @Composable @ReadOnlyComposable get() = hm(light = 0x475569, dark = 0x94A3B8)
        val fgSubtle: Color @Composable @ReadOnlyComposable get() = hm(light = 0x94A3B8, dark = 0x64748B)
        val fgInverted: Color @Composable @ReadOnlyComposable get() = hm(light = 0xFFFFFF, dark = 0x0F172A)
        val fgLink: Color @Composable @ReadOnlyComposable get() = hm(light = 0x2563EB, dark = 0x60A5FA)
        val borderDefault: Color @Composable @ReadOnlyComposable get() = hm(light = 0xE2E8F0, dark = 0x1E293B)
        val borderStrong: Color @Composable @ReadOnlyComposable get() = hm(light = 0xCBD5E1, dark = 0x334155)
        val borderFocus: Color @Composable @ReadOnlyComposable get() = hm(light = 0x3B82F6, dark = 0x3B82F6)
        val actionPrimaryBg: Color @Composable @ReadOnlyComposable get() = hm(light = 0x2563EB, dark = 0x3B82F6)
        val actionPrimaryHover: Color @Composable @ReadOnlyComposable get() = hm(light = 0x1D4ED8, dark = 0x60A5FA)
        val actionPrimaryFg: Color @Composable @ReadOnlyComposable get() = hm(light = 0xFFFFFF, dark = 0xFFFFFF)
        val statusDanger: Color @Composable @ReadOnlyComposable get() = hm(light = 0xDC2626, dark = 0xEF4444)
        val statusSuccess: Color @Composable @ReadOnlyComposable get() = hm(light = 0x16A34A, dark = 0x22C55E)
        val statusWarning: Color @Composable @ReadOnlyComposable get() = hm(light = 0xF59E0B, dark = 0xFBBF24)
    }

    object space {
        val _0: Dp = 0.dp
        val _1: Dp = 4.dp
        val _2: Dp = 8.dp
        val _3: Dp = 12.dp
        val _4: Dp = 16.dp
        val _5: Dp = 20.dp
        val _6: Dp = 24.dp
        val _8: Dp = 32.dp
        val _10: Dp = 40.dp
        val _12: Dp = 48.dp
        val _16: Dp = 64.dp
    }

    object radius {
        val sm: Dp = 4.dp
        val md: Dp = 8.dp
        val lg: Dp = 12.dp
        val xl: Dp = 16.dp
        val full: Dp = 9999.dp
    }

    object fontSize {
        val xs: TextUnit = 12.sp
        val sm: TextUnit = 14.sp
        val md: TextUnit = 16.sp
        val lg: TextUnit = 18.sp
        val xl: TextUnit = 20.sp
        val _2xl: TextUnit = 24.sp
        val _3xl: TextUnit = 30.sp
        val _4xl: TextUnit = 36.sp
    }

    object fontWeight {
        val regular: FontWeight = FontWeight(400)
        val medium: FontWeight = FontWeight(500)
        val semibold: FontWeight = FontWeight(600)
        val bold: FontWeight = FontWeight(700)
        val extrabold: FontWeight = FontWeight(800)
    }

    object lineHeight {
        val tight: Float = 1.25f
        val normal: Float = 1.5f
        val relaxed: Float = 1.625f
    }

    object typography {
        val headingLg = HmTextStyle(size = 30f, weight = 700, lineHeight = 1.25f)
        val headingMd = HmTextStyle(size = 24f, weight = 600, lineHeight = 1.25f)
        val headingSm = HmTextStyle(size = 20f, weight = 600, lineHeight = 1.25f)
        val bodyMd = HmTextStyle(size = 16f, weight = 400, lineHeight = 1.5f)
        val bodySm = HmTextStyle(size = 14f, weight = 400, lineHeight = 1.5f)
        val caption = HmTextStyle(size = 12f, weight = 400, lineHeight = 1.5f)
    }
}
